current_version = "0.2.0"

[[files]]
path = "pyproject.toml"

search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""


[[files]]
path = "src/atsphinx/qrcode/__init__.py"

search = "__version__ = \"{{current_version}}\""
replace = "__version__ = \"{{new_version}}\""


[[files]]
path = "CHANGES.rst"

search = """
Version {{current_version}}
========{{#sameLengthChars}}=@{{current_version}}{{/sameLengthChars}}
"""
replace = """
Version {{new_version}}
========{{#sameLengthChars}}=@{{new_version}}{{/sameLengthChars}}

:date: {{ nowFormat.dateISO }} (Asia/Tokyo)

Breaking changes
----------------

Features
--------

Fixes
-----

Others
------

Version {{current_version}}
========{{#sameLengthChars}}=@{{current_version}}{{/sameLengthChars}}
"""


[[files]]
path = ".github/release-body.md"
search = "Release atsphinx-qrcode v{{ current_version }}"
replace = "Release atsphinx-qrcode v{{ new_version }}"

[[files]]
path = ".github/release-body.md"
search = "- Changelog is https://github.com/atsphinx/qrcode/blob/v{{ current_version }}/CHANGES.rst"
replace = "- Changelog is https://github.com/atsphinx/qrcode/blob/v{{ new_version }}/CHANGES.rst"
